// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Letter struct {
	ID           int64
	NewsletterID int64
	Title        string
	Content      string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Newsletter struct {
	ID          int64
	Title       string
	Author      int64
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Subscriber struct {
	ID           int64
	UserID       int64
	NewsletterID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin sql.NullTime
}

type View struct {
	ID        int64
	LetterID  int64
	UserID    int64
	IpAddress pqtype.Inet
	CreatedAt time.Time
	UpdatedAt time.Time
}
